server:
  extraArgs:
    - --insecure

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.68.240
    annotations:
      metallb.universe.tf/address-pool: default-pool

  ingress:
    enabled: false
